name: emission
channels:
- conda-forge
- defaults
dependencies:
- branca=0.6.0
- folium=0.14.0
- ipython=8.12.0
- jedi=0.18.2
- jupyterlab=3.6.3
- matplotlib=3.7.1
- pip=23.3.1
- git
- pip:
  - git+https://github.com/JGreenlee/e-mission-common@0.4.0